webapp/user/models.py
from enum import unique
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from webapp.model import db, subs

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(50), unique=True)
    subscriptions = db.relationship('Share', secondary=subs, backref=db.backref('subscribers', lazy='dynamic'))

    
    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'

    def __repr__(self):
        return '<User {}>'.format(self.username)

webapp/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField('Имя пользователя',validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль',validators=[DataRequired()], render_kw={"class": "form-control"})
    submit = SubmitField('Отправить', render_kw={"class":"btn btn-dark"})

  

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webapp.user.models import User

class LoginForm(FlaskForm):
    username = StringField('Имя пользователя',validators=[DataRequired()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль',validators=[DataRequired()], render_kw={"class": "form-control"})
    remember_me = BooleanField('Запомнить меня', default=True, render_kw={"class": "from-check-input"})
    submit = SubmitField('Отправить', render_kw={"class":"btn btn-dark"})

class RegistrationForm(FlaskForm):
    username = StringField('Имя пользователя',validators=[DataRequired()], render_kw={"class": "form-control"})
    email = StringField('Электронная почта',validators=[DataRequired(), Email()], render_kw={"class": "form-control"})
    password = PasswordField('Пароль',validators=[DataRequired()], render_kw={"class": "form-control"})
    password2 = PasswordField('Повторите пароль',validators=[DataRequired(), EqualTo('password')], render_kw={"class": "form-control"})
    submit = SubmitField('Отправить', render_kw={"class":"btn btn-dark"})

    def validate_username(self, username):
        user_count = User.query.filter_by(username=username.data).count()
        if user_count > 0:
            raise ValidationError('Это имя уже занято!')

    def validate_email(self, email):
        mail_count = User.query.filter_by(email=email.data).count()
        if mail_count > 0:
            raise ValidationError('Пользователь с такой почтой уже существует!')

webapp/__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate
from webapp.model import db
from webapp.user.models import User
from webapp.user.views import blueprint as user_blueprint
from webapp.admin.views import blueprint as admin_blueprint
from webapp.main_page.views import blueprint as main_page_blueprint
from webapp.user_page.views import blueprint as user_page_blueprint



def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('../config.py')
    db.init_app(app)
    migrate = Migrate(app, db)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'

    app.register_blueprint(user_blueprint)
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(main_page_blueprint)
    app.register_blueprint(user_page_blueprint)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)
    
    return app

webapp/admin/views.py
from flask import Blueprint, render_template
from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')

@blueprint.route('/')
@admin_required
def admin_index():
    title = 'Панель управления'
    return render_template('admin/index.html', page_title=title)

webapp/main_page/views.py
from flask import Blueprint, render_template
from webapp.model import Share
from sqlalchemy import desc
from exchange_rates import dollar_value, euro_value, bitcoin_value
import indeces

blueprint = Blueprint('main_page', __name__)



@blueprint.route("/")
def index():
    title = "Инвестиции"
    fall = Share.query.order_by('todays_range').limit(5).all()
    height = Share.query.order_by(desc('todays_range')).limit(5).all()
    dollar = ('$ ' + str(dollar_value()))
    euro = ('€ ' + str(euro_value()))
    bitcoin = ('₿ ' + str(bitcoin_value()))
    idx = indeces.idx

    return render_template('main_page/index.html', page_title=title, height=height, fall=fall, 
    dollar=dollar, euro=euro, bitcoin=bitcoin, idx=idx
    )

webapp/user/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user
from webapp.user.forms import LoginForm, RegistrationForm
from webapp.user.models import User
from webapp.model import db

blueprint = Blueprint('user', __name__)

@blueprint.route("/login")
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_page.index'))
    title = "Авторизация"
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)

@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()
    
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Вы вошли на сайт')
            return redirect(url_for('main_page.index'))

    flash('Неправильное имя пользователя или пароль')
    return redirect(url_for('user.login'))

@blueprint.route('/logout')
def logout():
    logout_user()
    flash('Вы успешно разлогинились')
    return redirect(url_for('main_page.index'))

@blueprint.route('/register')
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main_page.index'))
    title = "Регистрация"
    form = RegistrationForm()
    return render_template('user/registration.html', page_title=title, form=form)

@blueprint.route('/process-reg', methods=['POST'])
def process_reg():
    form = RegistrationForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Добро пожаловать!')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for error in errors:
                flash('Ошибка в поле "{}": - {}'.format(
                    getattr(form, field).label.text,
                    error
                ))
        return redirect(url_for('user.register'))

webapp/user_page/views.py
from flask import Blueprint, render_template

blueprint = Blueprint('user_page', __name__, url_prefix='/user')

@blueprint.route("/")
def user():
    title = "Личный кабинет"
    return render_template('user_page/user.html', page_title=title)

    

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel= "stylesheet" type="text/css" href="{{ url_for('static',filename='css/main.css') }}">

    <title>{{ page_title }}</title>
  </head>
  <body>
    {% include 'menu.html' %}
    {% block content %}{% endblock %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

webapp/templates/index.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel= "stylesheet" type="text/css" href="{{ url_for('static',filename='css/main.css') }}">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container-fluid">
        <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
            <a href="" class="navbar-brand"><img src="static/img/logo.png" class="round"></a>    
          <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="#" class="nav-link px-2 link-dark">Курс доллара</a></li>
            <li><a href="#" class="nav-link px-2 link-dark">Курс евро</a></li>
            <li><a href="#" class="nav-link px-2 link-dark">ещё курс</a></li>
          </ul>
    
          <div class="col-md-3 text-end">
            <a href="/login"><button type="button" class="btn btn-outline-dark me-2">Вход</button></a>
            <button type="button" class="btn btn-dark">Регистрация</button>
          </div>
        </header>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-4"></div>
        <div class="col text-center">
          {% with messages = get_flashed_messages() %}
          {% if messages %}
          <div class="dark dark-warning" role="dark">
            {% for message in messages %}
              {{ message }}<br>
            {% endfor %}
          </div>
          {% endif %}
        {% endwith %}
        </div>
        <div class="col-4"></div>
      </div>
      <div class="row">
        <div class="col-4"></div>
        <div class="col text-center">
          <h2>Мировые индексы</h2>
        </div>
        <div class="col-4"></div>
      </div>
    </div>
    <div class="bd-example container-fluid">
      <div class="row">
        <div class="col">
        </div>
        <div class="col-8">
          <table class="table table-borderless table-sm table-striped">
            <thead class="table-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Индекс</th>
                <th scope="col">Посл. цена</th>
                <th scope="col">Макс. цена</th>
                <th scope="col">Мин. цена</th>
                <th scope="col">Изменение</th>
                <th scope="col">Изменение %</th>
                <th scope="col">Время</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">1</th>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
              </tr>
              <tr>
                <th scope="row">2</th>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
              </tr>
              <tr>
                <th scope="row">3</th>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
              </tr>
              <tr>
                <th scope="row">4</th>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
              </tr>
              <tr>
                <th scope="row">5</th>
                <td>1</td>
                <td>2</td>
                <td>3</td>
                <td>4</td>
                <td>5</td>
                <td>6</td>
                <td>7</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col">
        </div>
      </div> 
      <br>
      <div class="container-fluid">
        <div class="row">
          <div class="col-2">
          </div>
          <div class="col-2 text-center">
            <h5>Топ-5 выросших акций</h5>
          </div>
          <div class="col-3">
          </div>
          <div class="col-2 text-center">
            <h5>Топ-5 упавших акций</h5>
          </div>
          <div class="col-2">
          </div>
        </div>
        <div class="row">
          <div class="col-2">
          </div>
          <div class="col-3">
            <table class="table table-borderless table-sm table-striped">
              <thead class="table-success">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Название</th>
                  <th scope="col">Рост</th>
                  <th scope="col">Рост %</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                </tr>
                <tr>
                  <th scope="row">2</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                </tr>
                <tr>
                  <th scope="row">3</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                </tr>
                <tr>
                  <th scope="row">4</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                </tr>
                <tr>
                  <th scope="row">5</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="col-2">
          </div>
          <div class="col-3">
            <table class="table table-borderless table-sm table-striped">
              <thead class="table-danger">
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Название</th>
                  <th scope="col">Падение</th>
                  <th scope="col">Падение %</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <th scope="row">1</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                </tr>
                <tr>
                  <th scope="row">2</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>

                </tr>
                <tr>
                  <th scope="row">3</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                </tr>
                <tr>
                  <th scope="row">4</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                </tr>
                <tr>
                  <th scope="row">5</th>
                  <td>1</td>
                  <td>2</td>
                  <td>3</td>
                </tr>
              </tbody>
            </table>
          </div>
          <div class="col-2">
          </div>
        </div>
      </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

webapp/templates/login.html
<!doctype html>
<html lang="ru">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel= "stylesheet" type="text/css" href="{{ url_for('static',filename='css/main.css') }}">

    <title>{{ page_title }}</title>
  </head>
  <body>
    <div class="container-fluid">
      <br><br><br><br><br>
        <div class="row">
            <div class="col-5">
              {% with messages = get_flashed_messages() %}
                {% if messages %}
                <div class="alert alert-warning" role="alert">
                  {% for message in messages %}
                    {{ message }}<br>
                  {% endfor %}
                </div>
                {% endif %}
              {% endwith %}
            </div>
            <div class="col-2">
                <form action="{{ url_for('process_login') }}" method="POST">
                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.username.label }}
                        {{ form.username() }}
                    </div>
                    <div class="form-group">
                        {{ form.password.label }}
                        {{ form.password() }}
                    </div><br>
                    {{ form.submit }}
                </form>
            </div>
            <div class="col-5"></div>
        </div>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

webapp/templates/main_page/index.html
{% extends "base.html" %}

{% block content %}

  <div class="container-fluid">
    <div class="row">
      <div class="col-4"></div>
      <div class="col text-center">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="dark dark-warning" role="dark">
          {% for message in messages %}
            {{ message }}<br>
          {% endfor %}
        </div>
        {% endif %}
      {% endwith %}
      </div>
      <div class="col-4"></div>
    </div>
    <div class="row">
      <div class="col-4"></div>
      <div class="col text-center">
        <h3>Мировые индексы</h3>
      </div>
      <div class="col-4"></div>
    </div>
  </div>
  <div class="bd-example container-fluid">
    <div class="row">
      <div class="col"></div>
      <div class="col-8">
        <table class="table table-borderless table-sm table-striped">
          <thead class="table-dark">
            <tr>
              <th scope="col">Индекс</th>
              <th scope="col">Посл. цена</th>
              <th scope="col">Макс. цена</th>
              <th scope="col">Мин. цена</th>
              <th scope="col">Изменение</th>
              <th scope="col">Изменение %</th>
            </tr>
          </thead>
          <tbody>
            {% for value in idx %}
            <tr><td>{{ value['name'] }}</td>
            <td>{{ value['last'] }}</td>
            <td>{{ value['high'] }}</td>
            <td>{{ value['low'] }}</td>
            <td>{{ value['change'] }}</td>
            <td>{{ value['change_percentage'] }}</td></tr>
            {% endfor %}                    
          </tbody>
        </table>
      </div>
      <div class="col">
      </div>
    </div> 
    <br>
    <div class="container-fluid">
      <div class="row">
        <div class="col-2">
        </div>
        <div class="col-2 text-center">
          Топ-5 выросших акций
        </div>
        <div class="col-3">
        </div>
        <div class="col-2 text-center">
          Топ-5 упавших акций
        </div>
        <div class="col-2">
        </div>
      </div>
      <div class="row">
        <div class="col-2">
        </div>
        <div class="col-3">
          <table class="table table-borderless table-sm table-striped demotable">
            <thead class="table green">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Стоимость</th>
                <th scope="col">Рост %</th>
              </tr>
            </thead>
            <tbody>
              {% for el in height %}
              <tr>
                <td>{{ el.stock_symbol }}</td>
                <td>{{ el.prev_close }}</td>
                <td>{{ el.todays_range }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="col-2">
        </div>
        <div class="col-3">
          <table class="table table-borderless table-sm table-striped demotable">
            <thead class="table red">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Стоимость</th>
                <th scope="col">Падение %</th>
              </tr>
            </thead>
            <tbody>
              {% for el in fall %}
              <tr>
                <td>{{ el.stock_symbol }}</td>
                <td>{{ el.prev_close }}</td>
                <td>{{ el.todays_range }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        <div class="col-2">
        </div>
      </div>
    </div>
  </div>
{% endblock %}

webapp/templates/menu.html
<div class="container-fluid menu">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/" class="navbar-brand"><img src="static/img/logo.png" class="round"></a>    
      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <a class="nav-link link-dark">Курсы валют:</a>
        <a class="nav-link link-dark">{{ dollar }}</a>
        <a class="nav-link link-dark">{{ euro }}</a>
        <a class="nav-link link-dark">{{ bitcoin }}</a>
      </ul>

      <div class="col-md-3 text-end">
        {% if current_user.is_authenticated %}
        <a href="/user"><button type="button" class="btn btn-outline-dark me-2">Личный кабинет</button></a>
        <a href="/logout"><button type="button" class="btn btn-dark">Выйти</button></a>
        {% else %}
        <a href="/login"><button type="button" class="btn btn-outline-dark me-2">Вход</button></a>
        <a href="/register"><button type="button" class="btn btn-dark">Регистрация</button></a>
        {% endif %}
      </div>
    </header>
</div>

webapp/templates/user/login.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid">
    <br><br><br><br><br>
    <div class="row">
      <div class="col-12 text-center">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
          <div class="dark" role="dark">
            {% for message in messages %}
              {{ message }}<br>
            {% endfor %}
          </div>
          {% endif %}
        {% endwith %}
      </div>
      <div class="row">
          <div class="col-5">
          </div>
          <div class="col-2">
              <form action="{{ url_for('user.process_login') }}" method="POST">
                  {{ form.hidden_tag() }}
                  <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                  </div>
                  <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password() }}
                  </div><br>
                  <div class="form-group form-check text-center">
                    {{ form.remember_me() }}
                    {{ form.remember_me.label(class_="form-check-label") }}
                  </div>
                  <div class="text-center"> {{ form.submit }} </div>
              </form>
          </div>
          <div class="col-5"></div>
      </div>
    </div>
  </div>
{% endblock %}

webapp/templates/user/registration.html
{% extends "base.html" %}

{% block content %}
{% with messages = get_flashed_messages() %}
    {% if messages %}
        {% for message in messages %}
        <div class="dark text-center" role="dark">
            {{ message }}
        </div>
        {% endfor %}
    {% endif %}
{% endwith %}
  <div class="container-fluid">
    <br><br><br><br><br>
    <div class="row">
      <div class="col-12 text-center">
      </div>
      <div class="row">
          <div class="col-5">
          </div>
          <div class="col-2">
              <form action="{{ url_for('user.process_reg') }}" method="POST">
                  {{ form.hidden_tag() }}
                  <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                  </div>
                  <div class="form-group">
                    {{ form.email.label }}
                    {{ form.email() }}
                  </div>
                  <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password() }}
                  </div><br>
                  <div class="form-group">
                    {{ form.password2.label }}
                    {{ form.password2() }}
                  </div><br>
                  <div class="text-center"> {{ form.submit }} </div>
              </form>
          </div>
          <div class="col-5"></div>
      </div>
    </div>
  </div>
{% endblock %}